# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
evaluation_epsilon: 0.0

runner: "episode"
#runner: "parallel"
batch_size_run: 1

t_max: 2500000
#seed: 863137861
buffer_size: 5000
#log_interval: 10 # Log summary of stats after every {} timesteps


# update the target network every {} episodes
#target_update_interval_or_tau: 200
target_update_interval: 200

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False
use_rnn: True

# use the Q_Learner to train
standardise_returns: False
standardise_rewards: True
agent_output_type: "q"
double_q: True

mac: "tm_mac"
learner: "teammate_learner"
#learner: "MATUD_learner"
agent: "TM_agent"
#agent: "MATUD_agent"

mixer: "qmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

timesteps: 1  # diffusion timesteps
denoise_batch_size :  32
attention_hidden_size: 64
attention_hidden_dim: 32
Unet_lr: 0.0001

batch_size: 32  #
lr: 0.0005  # rl learning rate
lr_decre_step: 3000
lr_decre_gamma: 0.999

save_model: False
name: "TM_qmix"
